# --------------------------------------------------------------------
# GitHub configuration
# --------------------------------------------------------------------
githubConfigUrl: "https://github.com/joshyorko/arc-runner-custom-docker"  # Replace with your GitHub URL

githubConfigSecret: pre-defined-secret

# --------------------------------------------------------------------
# Runner scale set configuration
# --------------------------------------------------------------------
runnerScaleSetName: "arc-runner-custom-docker-runner-k8s"  # Name of the runner scale set



# --------------------------------------------------------------------
# Runner Pod template configuration
# --------------------------------------------------------------------
template:
  spec:
    dnsPolicy: None
    dnsConfig:
      nameservers: ["8.8.8.8", "1.1.1.1"]
    #imagePullSecrets:        # omit this block if your image is public
    #  - name: ghcr-login
    containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:2.324.0  # Replace with your image
        imagePullPolicy: Always
        command: ["/home/runner/run.sh"]
        resources:
          requests:
            cpu: "2"
            memory: "4Gi"
          limits:
            cpu: "8"
            memory: "16Gi"

maxRunners: 3

minRunners: 0

containerMode:
  type: "dind"