# GitHub Actions workflow to build and publish a custom runner image
name: Build and Push Custom Runner Image

on:
  workflow_dispatch:
    inputs:
      build_dir:
        description: 'Directory containing Dockerfile to build'
        required: true
        default: 'dind-custom-playwright'

jobs:
  build:
    name: Build and Push Image
    runs-on: arc-runner-custom-docker-runner-k8s
    # Use Docker-in-Docker service for building
    container:
      image: docker:24.0-dind
      options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: ${{ github.event.inputs.build_dir }}
          file: ${{ github.event.inputs.build_dir }}/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.event.inputs.build_dir }}:latest

      - name: Output values
        run: |
          echo "Using values from: builder-workflow/values.yaml"
          cat builder-workflow/values.yaml
